---
title: "R Notebook"
output: html_notebook
---

Intermediate R
```{r}
3 == (2+1)
"intermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"
```
Greater and less than
Al comparar palabras se toma el orden alfaabetico
```{r}
-6 * 5 + 2 >= -10 + 1
"raining" <= "table"
TRUE >  FALSE
"@" <= "?"
```
comparar vectores
```{r}
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 7, 5, 16, 8, 13, 14)

linkedin > 15
facebook <= 10

linkedin > facebook

views <- matrix(c(linkedin,facebook), nrow = 2, byrow = TRUE)
views

views == 13
views >= 16
```
Operadores logicos
```{r}
linkedin <= 10 & facebook == 13
linkedin <= 10 | facebook == 13
views > 11 & views <= 14
```
If statement 
else if
```{r}
medium <- "LinkedIn"
num_views <- 14

if(medium == "Linkedin"){
  print("Showing LinkendIn information")
}else{
  print("Unknown medium")
}

if(num_views > 15){
  print("Guau")
}else{
  print("Ohhh")
}

if(medium == "Linkedin"){
  print("Showing LinkendIn information")
}else if (medium == "Facebook") {
  print("Show Face info")
}else{
  print("Unknown medium")
}
```
Else if 2.0
```{r}
number <- 75
result <- ""

if (number < 10){
  if (number < 5){
    result <- "extra small"
  }else {
    result <- "small"
  }}else if (number < 100){
    result <- "medium"
  }else{
    result <- "large"
  }

print(result)
```
Loops
```{r}
speed <- 88

while (spped > 30){
  print("Slow down!")
  spped <- spped - 7
}

while (speed > 30){
  print(paste("Slow down!", speed))
  
  if (speed > 80){
    break
  }
  
  if(speed > 48){
    print("Slow down big time!")
    speed <- speed - 11
  }else{
    print("Slow down!")
    speed <- speed - 6
  }
}

speed


```
Ciclo For a vector
```{r}
linkedin2 <- c(16,9,13,5,2,17,14)

for(l in linkedin2){
  print(l)
}

for (i in 1:length(linkedin2)){
  print(linkedin2[i])
}
```
Ciclo For a list
```{r}
nyc <- list(pop=8405837, boroughts=c("Manhattan","Bronx","Brooklyn","Queens","State Island"), capital=FALSE)

for(n in nyc){
  print(n)
}

for(i in 1:length(nyc)){
  if(i==2){
    for(j in 1:length(nyc[[i]])){
      print(nyc[[i]][j])
    }
  }else{
    print(nyc[[i]])
  }
}
```
loop over a matrix
```{r}
views

for(row in 1:nrow(views)){
  for(col in 1:ncol(views)){
    print(paste("On row", row, "and column", col, "contains", views[row,col]))
  }
}

```

