---
title: "R Notebook"
output: html_notebook
---

Functions
```{r}
pow_two <- function(x, print_info=TRUE){
  y <- x^2
  if(print_info){
    print(paste(x, "to the power two equals", y))
  }
  return(y)
}

pow_two(3)
result <- pow_two(4)
result
```

Function Scoping
```{r}
pow_four <- function(x){
  z <- x^4
  return(z)
}

pow_four(2)
z
x
```
R passes arguments by value
```{r}
triple <- function(x){
  x <- 3*x
  x
}

a <- 5
triple(a)
a
```
Other type of parameters
```{r}
linkedin

interpret <- function(num_views){
  if(num_views > 15){
    print("You're pop")
    return(num_views)
  }else{
    print("Try to be more visible")
    return(0)
  }
}

num_views
interpret(linkedin[1])

interpret_all <- function(views, return_sum=TRUE){
  count <- 0
  
  for(v in views){
    count <- count + interpret(v)
  }
  if(return_sum){
    return(count)
  }else{
    return(NULL)
  }
}

interpret_all(linkedin)
```
Load an R package
```{r}
library(ggplot2)
qplot(mtcars$wt, mtcars$hp)
```
Use Apply with R
```{r}
temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2),c(5,7,9,4,2),c(-3,5,8,9,4),c(3,6,9,4,1))

select <- function(x) {
  print(paste("This collection contains total = ", sum(x)))
}

lapply(temp, min)

for(t in temp){
 print(min(t)) 
}

list <- lapply(temp, select)
list
```
lapply and anonimous functions
```{r}
(function(x){3*x})(9)
pioneers <- c("GAUSS:1777","BAYES:1702","PASCAL:1623","PEARSON:1857")
split <- strsplit(pioneers, ":")

split_low <- lapply(split, tolower)
split_low
split

names <- lapply(split_low, function(x){x[1]})
names
years <- lapply(split_low, function(x){x[2]})
years
```
Use lapply with additional arguments
```{r}
select_el <- function(x, index){
  x[index]
}
names <- lapply(split_low, select_el, 1)
names
years <- lapply(split_low, select_el, 2)
years

```
sapply
```{r}
extremes <- function(x){
  c(min=min(x), max=max(x))
}

lapply(temp, extremes)
sapply(temp, extremes)

temp2 <- list(1,2,3,4,5)
temp2

func_temp2 <- function(x){
  x
}

lapply(temp2, func_temp2)
sapply(temp2, func_temp2)
```
vapply
```{r}

basics <- function(x){
  c(min=min(x), mean=mean(x), max=max(x))
}

lapply(temp, basics)
sapply(temp, basics)
vapply(temp, basics, numeric(3))

temp3 <- c("Guatemala","Salvador","Honduras","Nicaragua")

unique_letters <- function(name){
  bane <- gsub(" ", "", name)
  letters <- strsplit(name, split = "")[[1]]
  unique(letters)
}

lapply(temp3, unique_letters)
sapply(temp3, unique_letters)
vapply(temp3, unique_letters, nchar(7))
```
Utilidades
```{r}
errors <- c(1.9, -2.6, 4.0, -9.5, -3.4, 7.3)
print(sum(abs(round(errors))))

?round

linkedin <- list(16, 9, 13, 5, 2, 17, 14)
facebook <- list(17, 7, 5, 16, 8, 13, 14)

li_vec <- unlist(linkedin)
fb_vec <- unlist(facebook)
class(li_vec)
li_vec

social_vec <- append(li_vec, fb_vec)

sort(social_vec, decreasing = TRUE)
```
grep & grepl
```{r}
emails <- c("john.doe@ivyleague.edu", "education@world.gov", "dalai.lama@peace.org", "invalid.edu", "quant@bigdatacollege.edu", "cookie.monster@sesame.tv")

grepl(pattern = "edu", x=emails)
grep(pattern = "edu", emails)

hits <- grep(pattern = "edu", emails)
emails[hits]

```

