---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

gapminder %>%
  summarize(medianLifeExp = median(lifeExp))

gapminder %>%
  filter(year == 1957) %>%
  summarize(medianLifeExp = median(lifeExp))

gapminder %>%
  filter(year == 1957) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))
```
```{r}
gapminder %>%
  group_by(year) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))
```
```{r}
gapminder %>%
  filter(year == 1957) %>%
  group_by(continent) %>%
  summarize(medianLifeExp = median(lifeExp), max(gdpPercap))
```
```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarize(medianLifeExp = median(lifeExp), maxgdp = max(gdpPercap))
```
```{r}
by_year <- gapminder %>%
  group_by(year) %>%
  summarize(medianLifeExp = median(lifeExp), maxgdp = max(gdpPercap))

by_year

ggplot(by_year, aes(x=year, y=medianLifeExp)) +
  geom_point()
```
```{r}
by_year_continent <- gapminder %>%
  group_by(continent, year) %>%
  summarize(mediangdpPercap = median(gdpPercap))

by_year_continent

ggplot(by_year_continent, aes(x=year, y=mediangdpPercap, color=continent)) +
  geom_point()
```
Type of Visualizations

Line Plots
```{r}
by_year <- gapminder %>%
  group_by(year) %>%
  summarize(mediangdpPercap = median(gdpPercap))

by_year

ggplot(by_year, aes(x=year, y=mediangdpPercap)) +
  geom_line()
```

```{r}
by_year_continent <- gapminder %>%
  group_by(year, continent) %>%
  summarize(mediangdpPercap = median(gdpPercap))

by_year_continent

ggplot(by_year_continent, aes(x=year, y=mediangdpPercap, color=continent)) +
  geom_line()
```
Bar Plots
```{r}
oceania_1952 <- gapminder %>%
  filter(continent == "Oceania", year == 1952)

oceania_1952

ggplot(oceania_1952, aes(x=country, y=gdpPercap, fill=country)) +
  geom_col()
```
Histogramas
```{r}
gapminder_1952 <- gapminder %>%
  filter(year == 1952) %>%
  mutate(pop_by_mil = pop/1000000)

gapminder_1952

ggplot(gapminder_1952, aes(x=pop_by_mil)) +
  geom_histogram(bins = 10)
```
```{r}
gapminder_1952 <- gapminder %>%
  filter(year == 1952)

gapminder_1952

ggplot(gapminder_1952, aes(x=pop)) +
  geom_histogram(bins = 25) +
  scale_x_log10()
```
Box Plots
```{r}
gapminder_1952

ggplot(gapminder_1952, aes(x=continent, y=gdpPercap)) + 
  geom_boxplot() +
    scale_y_log10()
```
Data manipulation with dplyr
```{r}
counties <- read_csv('counties.csv')
counties

```
```{r}
counties %>%
  dplyr::select(state, county, population, men, women) %>%
  mutate(proportion_men = men/population) %>%
  filter(population > 10000) %>%
  arrange(desc(proportion_men))

```





Summarizing
```{r}
counties
counties_selected <- counties %>%
  dplyr::select(county, population, income, unemployment)

counties_selected %>%
  summarize(min_population=min(population), max_unemployment=max(unemployment), average_income=mean(income))

counties_selected<- counties %>%
  dplyr::select(state, county, population, land_area)

counties_selected %>%
  group_by(state) %>%
  summarise(total_area=sum(land_area), total_population=sum(population))

counties_selected <- counties %>%
  dplyr::select(region, state, county, population)

counties_selected %>%
  group_by(region, state) %>%
  summarise(total_pop = sum(population)) %>%
  summarise(average_pop = mean(total_pop), median_pop = median(total_pop))
```

```{r}
counties_selected %>%
  group_by(region, state) %>%
  summarise(total_pop = sum(population)) %>%
  ungroup() %>%
  summarise(average_pop = mean(total_pop), median_pop = median(total_pop))
```
The top_n verb
```{r}
counties_selected <- counties %>%
  dplyr::select(region, state, county, metro, population, walk)

counties_selected %>%
  group_by(region) %>%
  top_n(1, walk)

counties_selected <- counties %>%
  dplyr::select(region, state, county, population, income)

counties_selected %>%
  group_by(region, state) %>%
  summarise(average_income = mean(income)) %>%
  top_n(1, average_income)

#Si quiero el top 1 de toda la informacion
counties_selected %>%
  group_by(region, state) %>%
  summarise(average_income = mean(income)) %>%
  ungroup() %>%
  top_n(1, average_income)

counties_selected %>%
  summarise(average_income = mean(income)) %>%
  top_n(1, average_income)
```
```{r}
counties_selected <- counties %>%
  dplyr::select(state, metro, population)

counties_selected %>%
  group_by(state, metro) %>%
  summarise(total_pop = sum(population)) %>%
  top_n(1, total_pop) %>%
  ungroup() %>%
  count(metro, wt=total_pop)
# con wt se muestra el dato requerido
```

